# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'file_picker', :path => '../.symlinks/plugins/file_picker/ios'

  # Add other pods you are using here

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
